theme = "varua"

[editor]
auto-save = true

[editor.gutters]
layout = ["line-numbers", "diff"]

[editor.gutters.line-numbers]
min-width = 0

[editor.soft-wrap]
enable = true
wrap-indicator = "⌉"

[keys.insert]
C-s = ":w"
C-f = "file_picker"

[keys.normal]
r = ":w"
f = "file_picker"
F = "file_picker_in_current_directory"
Y = "yank_main_selection_to_clipboard"
